"""Add delivery_route to order table

Revision ID: 44e762df9c79
Revises: a56ea3008b7a
Create Date: 2025-06-03 17:42:38.528463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e762df9c79'
down_revision: Union[str, None] = 'a56ea3008b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_route', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_route')
    # ### end Alembic commands ###
